routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::resource('korporat','korporatController');
Route::resource('program', 'ProgramController');
Route::resource('akun', 'AkunController');
Route::resource('proposal','proposalController');
Route::resource('kategorisasi','kategorisasiController');
Route::resource('bpdb','bpdbController');
Route::resource('data_master','data_masterController');

Route::get('/kategorisasi', 'kategorisasiController@index')->name('kategorisasi');



Route::get('/', function () {
    return view('index');
});

Route::get('/li_pro', function () {
    return view('li_pro');
});

Route::get('/login', function () {
    return view('login');
});

Route::get('/lipro_kor', function () {
    return view('lipro_kor');
});

Route::get('/bpdb', function () {
    return view('bpdb');
});

Route::get('/akun_pengguna', function () {
    return view('akun_pengguna');
});

Route::get('/data_master', function () {
    return view('data_masterView');
});

Route::get('/kategorisasi', function () {
    return view('kategorisasi');
});

resources/views/bpdb.blade.php
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>Admin BPDB</title>

    <!-- Bootstrap CSS CDN -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/css/bootstrap.min.css" integrity="sha384-9gVQ4dYFwwWSjIDZnLEWnxCjeSWFphJiwGPXr1jddIhOegiu1FwO5qRGvFXOdJZ4" crossorigin="anonymous">
    <!-- Our Custom CSS -->
    <link rel="stylesheet" href="style2.css">
    <!-- Scrollbar Custom CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.min.css">

    <!-- Font Awesome JS -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/solid.js" integrity="sha384-tzzSw1/Vo+0N5UhStP3bvwWPq+uvzCMfrN1fEFe+xBmv1C/AtVX5K0uZtmcHitFZ" crossorigin="anonymous"></script>
    <script defer src="https://use.fontawesome.com/releases/v5.0.13/js/fontawesome.js" integrity="sha384-6OIrr52G08NpOFSZdxxz1xdNSndlD4vdcf/q2myIUVO0VsqaGHJsB0RaBE01VTOY" crossorigin="anonymous"></script>

</head>

<body>

    <div class="wrapper">
        <!-- Sidebar  -->
        <nav id="sidebar">
            <div class="sidebar-header">
                <h3>SIMANPROS</h3>
            </div>

            <ul class="list-unstyled">
                <li>
                    <a href="#homeSubmenu" data-toggle="collapse" aria-expanded="false" class="dropdown-toggle">Administrator</a>
                    <ul class="collapse list-unstyled" id="homeSubmenu">
                        <li>
                            <a href="login">Keluar</a>
                        </li>
                    </ul>
                </li>
                <li>
                    <a href="bpdb">Dasbor</a>
                </li>
                <li>
                    <a href="proposal">Proposal</a>
                </li>
                <li>
                    <a href="akun">Akun Pengguna</a>
                </li>
                <li>
                    <a href="program">Program</a>
                </li>
            </ul>
        </nav>

        <!-- Page Content  -->
        <div id="content">

            <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <div class="container-fluid">
                    <button type="button" id="sidebarCollapse" class="btn btn-info">
                        <i class="fas fa-align-left"></i>
                    </button>
                    <button class="btn btn-dark d-inline-block d-lg-none ml-auto" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                        <i class="fas fa-align-justify"></i>
                    </button>
                    <h4>Dashboard Admin BPDB</h4>
                </div>
            </nav>
            <div class="container">
                <div class="row">
                    <div class="col-sm-12" id="kotak">
                        <div class="row">
                            <div class="col-sm-3" id="satu">
                        <h1 class="display-3 text-center">47</h1>
                        <h6 class="text-center">Korporat Terdaftar</h6>
                    </div>
                    <div class="col-sm-3" id="dua">
                        <h1 class="display-3 text-center">278</h1>
                        <h6 class="text-center">Program Disetujui</h6>
                    </div>
                    <div class="col-sm-3" id="tiga">
                        <h1 class="display-3 text-center">16</h1>
                        <h6 class="text-center">Program Berjalan</h6>
                    </div>
                    <div class="col-sm-3" id="empat">
                        <h1 class="display-3 text-center">4</h1>
                        <h6 class="text-center">Program Menunggu</h6>
                    </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- jQuery CDN - Slim version (=without AJAX) -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <!-- Popper.JS -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.0/umd/popper.min.js" integrity="sha384-cs/chFZiN24E4KMATLdqdvsezGxaGsi4hLGOzlXwp5UZB1LY//20VyM   2taTB4QvJ" crossorigin="anonymous"></script>
    <!-- Bootstrap JS -->
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.0/js/bootstrap.min.js" integrity="sha384-uefMccjFJAIv6A+rW+L4AHf99KvxDjWSu1z9VI8SKNVmz4sk7buKt/6v9KI65qnm" crossorigin="anonymous"></script>
    <!-- jQuery Custom Scroller CDN -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/malihu-custom-scrollbar-plugin/3.1.5/jquery.mCustomScrollbar.concat.min.js"></script>

    <script type="text/javascript">
        $(document).ready(function () {
            $("#sidebar").mCustomScrollbar({
                theme: "minimal"
            });

            $('#sidebarCollapse').on('click', function () {
                $('#sidebar, #content').toggleClass('active');
                $('.collapse.in').toggleClass('in');
                $('a[aria-expanded=true]').attr('aria-expanded', 'false');
            });
        });
    </script>
</body>

</html>

resources/views/li_pro.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="css/img/gaya.css">

    <title>Lihat Program</title>
  </head>
  <body>
    
    <!-- navbar -->
    <!-- navbar -->
    <nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-light img-fluid">
        <a class="navbar-brand">SIMANPROS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a href="index.php" class="nav-link ">Beranda<span class="sr-only"></span></a>
              </li>
              <li class="nav-item">
                <a href="li_pro" class="nav-link">Program</a>
              </li>
              <li class="nav-item">
                <a href="index.php#kontak" class="nav-link">Kontak</a>
              </li>
              </li>
              <li class="nav-item">
                <a href="login" class="nav-link">Login</a>
              </li>
            </ul>
          </div>
        </nav>
    <!-- akhir navbar -->

    <!-- lihat program -->
    <section class="lipro" id="lipro">
      <div class="container">
        <div class="row">
          <div class="col-sm-5 offset-sm-1">
            <h1>Lihat Program</h1>
            <p>Mungkin anda perlu untuk melihat beberapa program-program siaga bencana yang telah diajukan oleh korporasi sebelumnya</p>
          </div>
        </div>
      </div>
    </section>
    <!-- akhir lihat program -->

    <!-- cari program -->
    <nav class="navbar navbar-light bg-light justify-content-center">
      <form class="form-inline">
        <div class="input-group">
          <input type="text" class="form-control" placeholder="Cari Program" aria-label="Cari Program" aria-describedby="basic-addon2">
          <div class="input-group-append">
            <span class="input-group-text" id="basic-addon2">Cari</span>
          </div>
        </div>
      </form>
    </nav>
    <!-- akhir cari program -->

    <!-- isi -->
    <section class="isi" id="isi">
      <div class="container">
        <div class="row">
          <div class="col-sm-3">
            <h5>Fitur Pencarian : </h5>
            <div class="dropdown" width="100%">
              <button class="btn dropdown-toggle" type="button" id="pilih" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" >Pilih Perusahaan</button>
              <div class="dropdown-menu" aria-labelledby="pilih">
                <a href="#" class="dropdown-item">Microsoft</a>
                <a href="#" class="dropdown-item">Telkom</a>
                <a href="#" class="dropdown-item">Indofood</a>
              </div>
            </div>
            <div class="dropdown">
              <button class="btn dropdown-toggle" type="button" id="pilih2" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" width="100%">Pilih Program</button>
              <div class="dropdown-menu" aria-labelledby="pilih2" width="100%">
                <a href="#" class="dropdown-item">Gempa</a>
                <a href="#" class="dropdown-item">Tsunami</a>
                <a href="#" class="dropdown-item">Banjir</a>
                <a href="#" class="dropdown-item">Longsor</a>
              </div>
            </div>
          </div>
          <div class="col-sm-9">
          <div class="container">
            <nav class="navbar navbar-light bg-light">
              <span class="navbar-brand mb-0 h1" style="color: white;">Microsoft</span>
            </nav>
            <div class="row">
              <div class="col-sm-3">
                <img src="css/img/18.jpg" width="100%">
              </div>
              <div class="col-sm-9">
                <h6>Microsoft Indonesia</h6>
                <h3>Program Siaga Simulasi Bencana Vulkanik</h3>
                <p>Aktifitas vulkanik di Indonesia semakin hari semakin aktif. Oleh karena itu, Microsoft Indonesia bekerjasama dengan R&D Microsoft Corporation merancang program siaga simulasi untuk persiapan terhadap bencana vulkanik.</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-9 offset-sm-1">
              </div>
            </div> 
          </div>
            

            <nav class="navbar navbar-light bg-light">
              <span class="navbar-brand mb-0 h1" style="color: white;">Pertamina</span>
            </nav>
            <div class="row">
              <div class="col-sm-3">
                <img src="css/img/20.jpg" width="100%">
              </div>
              <div class="col-sm-9">
                <h6>Pertamina</h6>
                <h3>Pertolongan Petama kepada Korban Longsor</h3>
                <p>Pertamina beserta jajaran tim SAR Indonesia bekerjasama untuk membuat program tanggap darurat terhadap korban longsor.</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-9 offset-sm-1">
              </div>
            </div>

            <nav class="navbar navbar-light bg-light">
              <span class="navbar-brand mb-0 h1" style="color: white;">Indofood</span>
            </nav>
            <div class="row">
              <div class="col-sm-3">
                <img src="css/img/19.jpg" width="100%">
              </div>
              <div class="col-sm-9">
                <h6>Indofood Industries</h6>
                <h3>Edukasi dan Siaga Awan Panas Vulkanik</h3>
                <p>Dengan semakin banyaknya serangan awan panas, Indofood memutuskan untuk membuat program penanggulangan bencana awan panas dengan edukasi..</p>
              </div>
            </div>
            <div class="row">
              <div class="col-sm-9 offset-sm-1">
              </div>
            </div>

          </div>

        </div>
      </div>
    </section>
    <!-- akhir isi -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/login.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="css/img/gaya.css">

    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">

    <title>LOGIN</title>
  </head>
  <body id="badan">
    <!-- navbar -->
    <!-- navbar -->
    <nav class="navbar sticky-top navbar-expand-sm navbar-dark bg-light img-fluid">
        <a class="navbar-brand">SIMANPROS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item active">
                <a href="index.php" class="nav-link ">Beranda<span class="sr-only"></span></a>
              </li>
              <li class="nav-item">
                <a href="li_pro" class="nav-link">Program</a>
              </li>
              <li class="nav-item">
                <a href="index.php/#kontak" class="nav-link">Kontak</a>
              </li>
              </li>
              <li class="nav-item">
                <a href="login" class="nav-link">Login</a>
              </li>
            </ul>
          </div>
        </nav>
    <!-- akhir navbar -->

    <!-- login -->
    <div class="card" style="width: 20rem;">
      <div class="card-body">
        <h4 class="card-tittle text-center">Login</h4>

        <form action="{{ route('korporat.store') }}" method="post">
          {{ csrf_field() }}
          <div class="form-group text-center">
            <div class="input-group input-group-lg">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <span>
                    <i class="fa fa-envelope"></i>
                  </span>
                </div>
              </div>
              <input class="form-control" type="text" placeholder="Email address">
            </div>
          </div>
          <div class="form-group text-center">
            <div class="input-group input-group-lg">
              <div class="input-group-prepend">
                <div class="input-group-text">
                  <span>
                    <i class="fa fa-lock"></i>
                  </span>
                </div>
              </div>
              <input class="form-control" type="password" placeholder="Password">
            </div>
          </div>
        </div>
          <div class="form-group text-center">
            <div class="btn-group" role="group">
              <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">Masuk Sebagai</button>
              <div class="dropdown-menu" aria-labelledby="btnGroupDrop1">
                <a class="dropdown-item" href="lipro_kor">Korporat</a>
                <a class="dropdown-item" href="bpdb">BPDB</a>
              </div>
            </div>
            <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal" data-whatever="@mdo">Daftar</button>
            <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
              <div class="modal-dialog" role="document">
                <div class="modal-content">
                  <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Buat Akun Agar Bisa Mengajukan Program</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                    </button>
                  </div>
                  <div class="modal-body">

                    <form >
                      {{ csrf_field() }}
                      <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Nama Perusahaan</label>
                        <input type="text" class="form-control" id="recipient-name" name="nama_perusahaan" placeholder="Masukkan Nama Perusahaan">
                      </div>
                      <div class="form-group">
                        <label for="message-text" class="col-form-label">Bentuk Perusahaan</label>
                        <select class="form-control" name="bentuk_perusahaan">
                          <option>(Pilih Bentuk Perusahaan</option>
                          <option>PT (Perseroan Terbatas)</option>
                          <option>CV</option>
                          <option>Koperasi</option>
                          <option>BUMN</option>
                          <option>Pemerintah</option>
                        </select>
                      </div>
                      <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Email</label>
                        <input type="email" class="form-control" id="email_korporat" name="email" placeholder="Masukkan Alamat Email">
                      </div>
                      <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Password</label>
                        <input type="password" class="form-control" id="pass_korporat" name="password" placeholder="Masukkan Password">
                      </div>
                      <div class="form-group">
                        <label for="recipient-name" class="col-form-label">No. Telepon</label>
                        <input type="text" class="form-control" id="telp_korporat" name="no_telepon" placeholder="Masukkan Nomor Telepon">
                      </div>
                      <div class="form-group">
                        <label for="recipient-name" class="col-form-label">Website</label>
                        <input type="text" class="form-control" id="web_korporat" name="website" placeholder="Masukkan Alamat Website">
                      </div>
                   <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Batal</button>
                    <button type="submit" class="btn btn-primary">Daftar!</button>
                  </div>
                    </form>
                  </div>

                </div>
              </div>
            </div>
          </div>
        </form>
      </div>
    </div>
    <!-- halaman login -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>

resources/views/proposalView.blade.php
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="css/img/gaya.css">


    <title>Pengajuan Proposal</title>
  </head>
  <body>
    
    <!-- navbar -->
    <nav class="navbar sticky-top navbar-expand-lg navbar-dark bg-light">
          <a class="navbar-brand">SIMANPROS</a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarSupportedContent">
            <ul class="navbar-nav">
              <li class="nav-item">
                <a href="li_pro" class="nav-link">Program</a>
              </li>
              <li class="nav-item active">
                <a href="proposal" class="nav-link active">Pengajuan</a>
              </li>
              <li class="nav-item">
                <a href="login" class="nav-link">Logout</a>
              </li>
            </ul>
          </div>
        </nav>
    <!-- akhir navbar -->

    <!-- lihat program -->
    <section class="lipro" id="lipro">
      <div class="container">
        <div class="row">
          <div class="col-sm-5 offset-sm-1">
            <h1>Ajukan Proposal Program Anda</h1>
            <p>Jika anda memiliki program siaga bencana baru, ajukan program tersebut disini</p>
          </div>
        </div>
      </div>
    </section>
    <!-- akhir lihat program -->

    <!-- alur pengajuan -->
    <section class="alur" id="alur">
      <div class="row">
        <div class="col-sm-12">
          <h3 class="text-center">Alur Pengajuan Proposal</h3>
        </div>
      </div>
      <div class="row">
        <div class="col-sm-4 text-center">
          <img src="css/img/10.png">
          <h5 class="text-center">Buat Akun Anda!</h5>
          <p class="text-center">Buatlah akun anda agar bisa mengajukan proposal program baru</p>
        </div>
        <div class="col-sm-4 text-center">
          <img src="css/img/11.png">
          <h5 class="text-center">isi Form Pengajuan</h5>
          <p class="text-center">isi form prngajuan sesuai dengan formatnya</p>
        </div>
        <div class="col-sm-4 text-center">
          <img src="css/img/12.png">
          <h5 class="text-center">Unggah Proposal Anda</h5>
          <p class="text-center">Unggah proposal anda untuk segera diproses</p>
        </div>
      </div>
    </section>
    <!-- akhir alur pengajuan -->

    <!-- form pengajuan -->
    <section class="aju" id="aju">
      <div class="container">
        <div class="row">
          <h1>Halo !</h1>
        </div>
        <div class="row">
          <h4>Silahkan isi form untuk mengajukan program baru</h4>
        </div>
       

        

          <form action="{{ route('proposal.store') }}" method="post">
            {{ csrf_field() }}

        <div class="row">
          <div class="col-sm-4" name="kategori">
            <h5>Kategori</h5>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="kategori" id="exampleRadios1" value="option1" checked>
              <label class="form-check-label" for="exampleRadios1">Gempa Bumi</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="kategori" id="exampleRadios2" value="option2">
              <label class="form-check-label" for="exampleRadios2">Tanah Longsor</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="kategori" id="exampleRadios2" value="option2">
              <label class="form-check-label" for="exampleRadios2">Gunung Meletus</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="kategori" id="exampleRadios2" value="option2">
              <label class="form-check-label" for="exampleRadios2">Banjir</label>
            </div>
            <div class="form-check">
              <input class="form-check-input" type="radio" name="kategori" id="exampleRadios2" value="option2">
              <label class="form-check-label" for="exampleRadios2">Angin Puting Beliung</label>
            </div>
        </div>
        <div class="col-sm-8">
            <div class="form-group">
              <label>Judul Program</label>
              <input type="text" class="form-control" placeholder="Judul Program" name="judul">
            </div>
            <div class="form-group">
              <label>Tujuan Program</label>
              <input type="text" class="form-control" placeholder="Tujuan Program" name="tujuan">
            </div>
            <div class="form-group">
              <label>Sasaran Program</label>
              <input type="text" class="form-control" placeholder="Sasaran Program" name="sasaran_program">
            </div>
            <div class="form-group">
              <label>Lokasi Program</label>
              <input type="text" class="form-control" placeholder="Lokasi Program" name="lokasi">
            </div>
            <div class="form-group">
              <label>Biaya Program</label>
              <input type="text" class="form-control" placeholder="Biaya Program" name="biaya">
            </div>
            <div class="text-center">
              <h5>Lampirkan File Anda di Bawah</h5>
              <p>Hanya format berikut yang diperboehkan : .doc, .pptx, .pdf, .jpg, .mp4</p>
            </div>
                        <form>
              <div class="form-group"><label for="exampleFormControlFile1">Pilih File</label>
                <input type="file" class="form-control-file" id="uploadfile" name="file">
              </div>
            </form>
             <div class="col-sm-12 text-center">
          <button type="submit" class="btn btn-primary">Ajukan Program</button>
        </div>

          </form>
        </div>
      </div>
      <div class="row">
       
      </div>
    </div>
    </section>
    <!-- akhir form pengajuan -->

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  </body>
</html>